In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
data = load_breast_cancer()
print(type(data))
print(dir(data))

<class 'sklearn.utils._bunch.Bunch'>
['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [3]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 

In [4]:
X = data.data
# print(X)

y = data.target
# print(y)

print(X.shape)  #(569, 30) 데이터 개수, 열
print(len(y))   #569 데이터 569개

(569, 30)
569


In [48]:
# 데이터를 학습용과 테스트용으로 분리/데이터 분할(학습 80%, 테스트 20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, y_train.shape)     #(455, 30) (455,)
print(X_test.shape, y_test.shape)       #(114, 30) (114,)


ValueError: Found input variables with inconsistent numbers of samples: [569, 1797]

In [47]:
# 모델 학습(로지스틱 회귀)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
print(dir(model))

ValueError: Found input variables with inconsistent numbers of samples: [455, 1347]

In [9]:
# 예측 (클래스 예측 및 확률 예측)
y_pred = model.predict(X_test)
print(y_pred)       # 에측 결과 
print()

# print(y_pred==y_test)
print(pd.Series(y_pred==y_test).unique())
print(pd.Series(y_pred==y_test).value_counts())
print()

y_prob = model.predict_proba(X_test)
print(y_prob)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 0 0]

[ True False]
True     109
False      5
Name: count, dtype: int64

[[1.21238266e-01 8.78761734e-01]
 [9.99999970e-01 3.03624981e-08]
 [9.98405090e-01 1.59490988e-03]
 [1.21353825e-03 9.98786462e-01]
 [1.39796565e-04 9.99860203e-01]
 [1.00000000e+00 1.94458720e-10]
 [1.00000000e+00 6.09483521e-11]
 [9.80773102e-01 1.92268979e-02]
 [1.58520339e-02 9.84147966e-01]
 [5.63029459e-03 9.94369705e-01]
 [7.04321239e-02 9.29567876e-01]
 [9.99193285e-01 8.06714616e-04]
 [1.10171295e-02 9.88982871e-01]
 [8.24174930e-01 1.75825070e-01]
 [7.79253365e-04 9.99220747e-01]
 [9.98272428e-01 1.72757217e-03]
 [1.18193344e-03 9.98818067e-01]
 [1.18481436e-05 9.99988152e-01]
 [5.99658938e-07 9.99999400e-01]
 [9.99999288e-01 7.11997904e-07]
 [1.71640882e-01 8.28359118e-01]
 [7.63

In [10]:
cm = confusion_matrix(y_test, y_pred)       #정답, 예측값
print(cm)

[[39  4]
 [ 1 70]]


In [19]:
#평가 지표 계산
acc = accuracy_score(y_test, y_pred)   # (정답, 예측)
acc = precision_score(y_test, y_pred)  # (positive예측에서 진짜 positive인 경우)
rec = recall_score(y_test, y_pred)     # (positive정답에서 positive로 예측한 경우)
f1 = f1_score(y_test, y_pred)         # (정밀도와 재현율의 조화평균)

print('평가 지표')
print(f'Accuracy: {acc}')
print(f'Precision: {rec}')
print(f'Recall: {rec}')
print(f'F1 Score: {f1}')


평가 지표
Accuracy: 0.9459459459459459
Precision: 0.9859154929577465
Recall: 0.9859154929577465
F1 Score: 0.9655172413793104


## 데이터가 불균형일 때 발생되는 문제

불균형한 이진 분류로 만들기 위해 숫자 '7'만 True 나머지 숫자는 False로 설정

- 마찬가지로 fit은 아무것도 하지 않음
- predict에서는 무조건 0을 반환함
- 모든 예측을 다 0으로 하는 것! (모두 7이 아닌 다른 숫자라고 예측)
- 당연히 모델로서 말이 안 되는데 이것의 정확도를 측정

In [20]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [26]:
class MyFakeClassifier(BaseEstimator):
    def fit(self,X,y):
        pass

    # 입력값으로 들어오는 X 데이터 셋의 크기만큼 모두 0값으로 만들어서 반환
    def predict(self,X):
        return np.zeros( (len(X), 1) , dtype=bool)

# 사이킷런의 내장 데이터 셋인 load_digits()를 이용하여 MINIST 숫자 데이터 셋을 로딩
digits = load_digits()

print(digits.data.shape)  #(1797, 64) 1797개의 데이터, 8*8=64개의 픽셀
print(digits.target.shape)  #(1797,) 1797개의 정답 레이블
print(np.unique(digits.target))  #0~9까지의 숫자
print(digits.DESCR)
print(digits.data[0])  #첫번째 데이터
print(digits.target[0])  #첫번째 데이터의 정답 레이블

(1797, 64)
(1797,)
[0 1 2 3 4 5 6 7 8 9]
.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 1797
:Number of Attributes: 64
:Attribute Information: 8x8 image of integer pixels in the range 0..16.
:Missing Attribute Values: None
:Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
:Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are co

In [ ]:
print(digits.target)
#숫자가 7인 경우 True, 아니면 False로 변환
# 이를 1과 0으로 변환하기 위해서 astype(int)를 사용
y = (digits.target == 7).astype(int)  #7이면 1, 아니면 0으로 변환

print(len(y))

print(pd.Series(y).value_counts())  #7인 경우와 아닌 경우의 개수 확인

x_train, x_test, y_train, y_test = train_test_split(digits.data, y, random_state=11)

# 0    1213
# 1     134
print(pd.Series(y_train).value_counts()) 

# 0    405
# 1     45
print(pd.Series(y_test).value_counts())


[0 1 2 ... 8 9 8]
1797
0    1618
1     179
Name: count, dtype: int64
0    1213
1     134
Name: count, dtype: int64
0    405
1     45
Name: count, dtype: int64


In [ ]:
fake_clf = MyFakeClassifier()
fake_clf.fit(x_train, y_train)

fake_pred = fake_clf.predict(x_test)

print('모든 예측값이 0으로 하여도 정확도는 : {:.3f}'.format(accuracy_score(y_test, fake_pred)))

cf = confusion_matrix(y_test, fake_pred)
print(f'Accuracy: {cf}')

f1 = f1_score(y_test, fake_pred)
print(f'F1 Score: {f1}')

prec = precision_score(y_test, fake_pred)
print(f'Precision: {prec}')



모든 예측값이 0으로 하여도 정확도는 : 0.900
Accuracy: [[405   0]
 [ 45   0]]
F1 Score: 0.0
Precision: 0.0


c:\sk-encore\data_collection_worksapce\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [27]:
print(digits.data[0].reshape(8,8))  #첫번째 데이터의 픽셀값을 8*8로 변환
print(digits.data[0].reshape(8,8).shape)  #(8, 8)

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]
(8, 8)


In [46]:
# [해결방법]
# HTML 다이어그램 출력 기능을 끄고 텍스트로 표시
# import platform
# import sklearn
# print(platform.system())
# if platform.system()=='Windows':
#     sklearn.set_config(display='text')


# 모델 학습(로지스틱 회귀)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train);
# print(dir(model))

ValueError: Found input variables with inconsistent numbers of samples: [455, 1347]

- 모든 예측을 0으로 했지만, 0 (7이 아닌 숫자)이 1 (숫자 7)보다 훨씬 많은 불균형 데이터였기 때문에, 정확도가 무려 90%가 나왔다.

- 이렇게 두 가지 예제로 불균형 데이터에서 정확도의 성능 평가지표로서 한계를 보였다