【모델 예측 성능평가】
- 모델 예측 성능평가하는 학습모델이 실제값을 얼마나 정확하게 맞추었는지를  나타내는 것이다.
- 머신러닝 모델은 여러가지 방법으로 예측 성능을 평가할 수 있다.
- 이를 성능평가지표(Evaluation Metric)라 하며, 일반적으로 분석 알고리즘이 회귀분석인지 분류분석인지에 따라 여러 종류가 있다.
-  회귀분석 성능평가 종류

|종류	|	잔차 계산 |	이상치 영향|
|---|---|---|
|MAE	(Mean Absolute Error) |	Absolute Value|	Yes|
|MSE	(Mean Squared Error)	|Square|	No|
|RMSE	(Root Mean Squared Error) |	Square|	No|
|MAPE	(Mean Absolute Percentage Error)	| Absolute Value|	 Yes|
|MPE	(Mean Percentage Error)	|N/A	|Yes|


### 1. 평균 절대 오차 (MAE : Mean Absolute Error)
- 실제 값과 예측 값의 차이(Error)를 절대값으로 변환해 평균한다.
- MAE는 에러에 절대값을 취하기 때문에 에러의 크기 그대로 반영된다.
- 에러에 따른 손실이 선형적으로 올라갈 때 적합하다.
- 0에 가까울수록 좋은 모델이라고 할 수 있다.
- 이상치에 영향을 받는다.
- 회귀평가를 위한 지표로 주로 쓰인다


$$ MAE = \frac{1}{n}\sum_{i=1}^{n} |Y_i-\hat{Y_i}|$$


python으로 MAE 구현

In [1]:
print('d')

d


In [2]:
import numpy as np

testVal = np.array([1,   1.7,  1.5])  # 실제값
predVal = np.array([1.1,   2,   1.7]) # 예측값
print(testVal-predVal)



[-0.1 -0.3 -0.2]


sklearn의 mean_absolute_error( )로 계산

In [6]:
from sklearn.metrics import mean_absolute_error
testVal = np.array([1,   1.7,  1.5])
predVal = np.array([1.1,   2,   1.7])
print(testVal-predVal)


[-0.1 -0.3 -0.2]


### 2 평균 제곱 오차(MSE : Mean Squared Error)

- 실제값과 예측값의 차이를 제곱해 평균한다.
- 예측값과 실제값 차이의 면적의 평균과 같다.
- 이상값(특이값)이 존재하면 수치가 많이 늘어난다.
- MSE가 0에 가까울수록 추측한 값이 원본에 가까운 것이기 때문에 정확도가 높다고 할 수 있다.


 $$ MSE = \frac{1}{n}\sum_{i=1}^{n} (Y_i-\hat{Y_i})^2$$


python으로 mse으로 구현

In [12]:
import numpy as np

testVal = np.array([1,   1.7,  1.5])
predVal = np.array([1.1,   2,   1.7])


mse_custom = sum((testVal - predVal) ** 2) / len(testVal)
print(mse_custom)

0.04666666666666667


 sklearn의 mean_squared_error( )로 계산

In [9]:
import sklearn.metrics
print(dir(sklearn.metrics))

['ConfusionMatrixDisplay', 'DetCurveDisplay', 'DistanceMetric', 'PrecisionRecallDisplay', 'PredictionErrorDisplay', 'RocCurveDisplay', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_base', '_classification', '_dist_metrics', '_pairwise_distances_reduction', '_pairwise_fast', '_plot', '_ranking', '_regression', '_scorer', 'accuracy_score', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'auc', 'average_precision_score', 'balanced_accuracy_score', 'brier_score_loss', 'calinski_harabasz_score', 'check_scoring', 'class_likelihood_ratios', 'classification_report', 'cluster', 'cohen_kappa_score', 'completeness_score', 'confusion_matrix', 'confusion_matrix_at_thresholds', 'consensus_score', 'coverage_error', 'd2_absolute_error_score', 'd2_brier_score', 'd2_log_loss_score', 'd2_pinball_score', 'd2_tweedie_score', 'davies_bouldin_score', 'dcg_score', 'det_curve', 'euclidean_distances', 'explained_variance_s

In [10]:
from sklearn.metrics import mean_squared_error
testVal = np.array([1,   1.7,  1.5])
predVal = np.array([1.1,   2,   1.7])

print(testVal-predVal)

[-0.1 -0.3 -0.2]


### 3 루트 평균 제곱근 오차(RMSE)

- 실제값과 예측값의 차이를 제곱해 평균한 것에 루트를 씌운다
- 에러에 제곱을 하면 에러가 클수록 그에 따른 가중치가 높이 반영된다.
- 이때, 손실이 기하급수적으로 증가하는 상황에서 실제 오류평균보다 값이 더 커지지 않도록 하기 위해 사용한다.


 $$ RMSE = \sqrt{\frac{1}{n}\sum_{i=1}^{n} (Y_i-\hat{Y_i})^2}$$

python으로 rmse 구현

In [17]:
import numpy as np

testVal = np.array([1,   1.7,  1.5])
predVal = np.array([1.1,   2,   1.7])

# rmse_custom = np.sqrt(sum((testVal - predVal) ** 2) / len(testVal))
# print(rmse_custom)
root_mse_squared = mean_squared_error(testVal, predVal, squared=False)
print(root_mse_squared)

TypeError: got an unexpected keyword argument 'squared'

sklearn의 mean_squared_error( )로 계산

In [7]:
print(sklearn.__version__)

1.9.0


In [8]:
from sklearn.metrics import  root_mean_squared_error
testVal = np.array([1,   1.7,  1.5])
predVal = np.array([1.1,   2,   1.7])



### 4 평균 제곱 로그 오차 (MSLE : Mean Squared Log Error)

- 실제값과 예측값의 차이를 제곱해 평균한 것에 로그를 적용한다.
- RMSE와 같이 손실이 기하급수적으로 증가하는 상황에서 실제 오류평균보다 값이 더 커지지 않도록 해준다.
 $$ MSLE = \log(\frac{1}{n}\sum_{i=1}^{n} (Y_i-\hat{Y_i})^2)$$

python으로 msle 구현

In [18]:
import numpy as np

testVal = np.array([1, 2, 3, 2, 3, 5, 4, 6, 5, 6, 7])
predVal = np.array([1, 1, 2, 2, 3, 4, 4, 5, 5, 7, 7])

# np.log1p(x)는 np.log(x + 1)과 같다.
# 값이 0일 때 log(0) = -∞ 가 되는 것을 방지하기 위해 모든 값에 1을 더해주는 과정이다.
msle_custom = np.mean((np.log1p(testVal) - np.log1p(predVal)) ** 2)
print(msle_custom)


0.029272467607503516


In [10]:
from sklearn.metrics import mean_squared_log_error

testVal =  np.array([1, 2, 3, 2, 3, 5, 4, 6, 5, 6, 7])
predVal = np.array([1, 1, 2, 2, 3, 4, 4, 5, 5, 7, 7])

