In [1]:
import numpy as np
import pandas as ps
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import recall_score, f1_score, confusion_matrix



In [3]:
data = load_breast_cancer()
print(type(data))
print(dir(data))

<class 'sklearn.utils._bunch.Bunch'>
['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [13]:
import pandas as pd

In [16]:
print(ps.Series(y_pred==Y_test).unique())
print(ps.Series(y_pred==Y_test).value_counts())

[ True False]
True     109
False      5
Name: count, dtype: int64


In [18]:
print(pd.Series(y_pred==Y_test).unique())
print(pd.Series(y_pred==Y_test).value_counts())

[ True False]
True     109
False      5
Name: count, dtype: int64


In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'y' is not defined

In [20]:
# 예측 (클래스 예측 및 확률 예측)
y_pred = model.predict(X_test)
print(Y_pred)       # 에측 결과 
print()

# print(y_pred==y_test)
print(pd.Series(Y_pred==Y_test).unique())
print(pd.Series(Y_pred==Y_test).value_counts())
print()

y_prob = model.predict_proba(X_test)
print(Y_prob)

NameError: name 'Y_pred' is not defined

In [13]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

NameError: name 'X_train' is not defined

In [4]:
%whos

Variable             Type        Data/Info
------------------------------------------
LogisticRegression   type        <class 'sklearn.linear_mo<...>stic.LogisticRegression'>
accuracy_score       function    <function accuracy_score at 0x0000022942131940>
confusion_matrix     function    <function confusion_matrix at 0x0000022942131A80>
data                 Bunch       {'data': array([[1.799e+0<...> 'sklearn.datasets.data'}
f1_score             function    <function f1_score at 0x0000022942132200>
load_breast_cancer   function    <function load_breast_can<...>er at 0x000002292DC084A0>
np                   module      <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
plt                  module      <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
precision_score      function    <function precision_score at 0x0000022942132A20>
ps                   module      <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
recall_score         function    <function recall_score at 

In [10]:
y_pred = model.predict(X_test)
print(y_pred)
print(y_pred == y_test)
print(pd.Series(y_pred==y_test).unique())
print(pd.Series(y_pred==y_test).value_counts())
y_prob = model.predict_proba(X_test)
print(y_prob)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 0 0]


NameError: name 'y_test' is not defined

In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

NameError: name 'y_test' is not defined

In [22]:
#예측 (클래스 예측및 확률 예측)

Y_pred = model.predict(X_test)
print(Y_pred)
# print(y_pred == y_test)
print(pd.Series(y_pred == y_test).unique())
print(pd.Series(y_pred == y_test).value_counts())
y_prob = model.predict_proba(X_test)
print(y_prob)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 0 0]


NameError: name 'pd' is not defined

In [6]:
X = data.data
print(X)

Y = data.target
print(Y)

print(X.shape)
print(len(Y))



[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [22]:
# 데이터를 학습용과 테스트용으로 분리/데이터 분할 (학습 80%, 테스트 20%)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(455, 30) (455,)
(114, 30) (114,)


In [8]:
model = LogisticRegression(max_iter=10000)
model.fit(X_train, Y_train)
print(dir(model))

['C', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__sklearn_tags__', '__str__', '__subclasshook__', '__weakref__', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_get_class_level_metadata_request_values', '_get_doc_link', '_get_fitted_attr_html', '_get_metadata_request', '_get_param_names', '_get_params_html', '_html_repr', '_init_callback_context', '_parameter_constraints', '_predict_proba_lr', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_validate_params', 'class_weight', 'classes_', 'coef_', 'decision_function', 'densify', 'dual', 'fit', 'fit_intercept', 'get_metadata_routing', 'get_params', 'intercept_', 'intercept_scali

In [2]:
#모델 학습(로지스틱 회귀)
model = LogisticRegression(max_iter=10000)
model.fit(X_train, Y_train)
print('')

NameError: name 'LogisticRegression' is not defined

In [9]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - 