In [1]:
# NumPy 사용
import numpy as np

In [2]:
import numpy as np
print(np.__version__)

2.5.1


In [3]:
#!pip list | grep numpy
# windows에는 기본적으로 grep대시 findstr이 탑재되어 있음
!uv  pip list | findstr numpy   

numpy                   2.5.1


In [6]:
import time

# 1,000만 개의 원소를 가진 파이썬 리스트 생성
py_list = list(range(10000000))

# 연산 시간 측정시작
start_time = time.time()

# for 루프 또는 컴프리헨션을 이용한 각 원소 2배 연산
result_list = [x * 2 for x in py_list]

print(f"파이썬 리스트 소요 시간: {time.time() - start_time:.4f} 초")

파이썬 리스트 소요 시간: 1.4965 초


In [7]:
np.arange(10)  # ([start,] stop [,step])

# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 15.6 ms
Wall time: 20.2 ms


499999500000

In [5]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: total: 31.2 ms
Wall time: 36.8 ms


499999500000

In [8]:
import numpy as np

# 1,000만 개의 원소를 가진 NumPy 배열 생성
np_array = np.arange(10000000)

# 연산 시간 측정시작
start_time = time.time()

# 반복문 없이 배열 전체에 바로 2를 곱하는 벡터화 연산
result_array = np_array * 2

print(f"NumPy 배열 소요 시간: {time.time() - start_time:.4f} 초")


NumPy 배열 소요 시간: 0.0844 초


In [9]:
np.arange(10)  # ([start,] stop [,step])
# numpy을 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: total: 0 ns
Wall time: 5.04 ms


np.int64(499999500000)

In [10]:
import numpy as np

# 2행 3열의 수치형 2차원 배열 정의
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 차원:", arr.ndim, np.ndim(arr))   # 출력: 2
print("배열의 형태:", arr.shape, np.shape(arr))  # 출력: (2, 3)
print("원소 총 개수:", arr.size, np.size(arr))  # 출력: 6
print("데이터 타입:", arr.dtype)  # 출력: int64

# 정수형 데이터를 실수형(Float) 데이터 타입으로 강제 변환
float_arr = arr.astype(np.float64)
print("변경된 타입:", float_arr.dtype)  # 출력: float64


배열의 차원: 2 2
배열의 형태: (2, 3) (2, 3)
원소 총 개수: 6 6
데이터 타입: int64
변경된 타입: float64


In [12]:

import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.dtype)            # int64 : 정수 64bit => 8byte

<class 'numpy.ndarray'>
int64


In [13]:
import numpy as np

int64_a = np.array([1, 2, 3])
print(int64_a.dtype )
float32_b = int64_a.astype(np.float32)
print(float32_b )                 # array([1., 2., 3.])
print(float32_b .dtype)           # dtype('float32')

int64
[1. 2. 3.]
float32


In [14]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])
print(a)           # [1 2 3]
print(dir(a))
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # print(a.shape)

[1 2 3]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '_

In [15]:
# 2차원 배열 = 행렬
b = np.array([[1,2],[3,4]]) # 2행 2열
print(b)                # [[1 2][3 4]]
print(dir(b))
print(type(b))           # <class 'numpy.ndarray'>
print(b.shape)           # (2, 2)

[[1 2]
 [3 4]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd

In [16]:
# 3차원 배열 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 2층(공간, 면), 2행 , 2열
print(c)          # [[[1,2][3,4]]  [[5,6][7,8]]]
print(dir(c))
print(type(c))     # <class 'numpy.ndarray'>
print(c.shape)     # (2, 2, 2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__

In [17]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 즉 같은 데이터 타입만 저장 할 수 있다.
a = np.array([1, '2', 3])
print(a)             # ['1' '2' '3']

['1' '2' '3']


In [18]:
a = np.array(['a', 1, True])
print(a)              # array(['a', '1', 'True'], dtype='<U21')

['a' '1' 'True']


In [19]:
a = np.array([True, False, True])
print(a)               # array([ True, False,  True])

[ True False  True]


In [20]:
a = np.array([True, False, True, 0, 1]) # False -> 0, True -> 1
print(a)                 #  array([1, 0, 1, 0, 1])

[1 0 1 0 1]


In [30]:
a = np.zeros(3) # [0. 0. 0.]
print(a)

[0. 0. 0.]


In [31]:
a = np.zeros((2,3))      #[[0. 0. 0.][0. 0. 0.]]
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [32]:
a = np.ones(3)
print(a)        # [1. 1. 1.]

[1. 1. 1.]


In [34]:
a= np.ones((2,3))
print(a)         # [[1. 1. 1.][1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
a = np.eye(3)
print(a)               # [[1. 0. 0.][0. 1. 0.][0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 3행 2열의  단위 행렬 생성
a = np.eye(3, 2) # 3행 2열
print(a)                 # [[1. 0.][0. 1.][0. 0.]]

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [27]:
# 1를 시작되는 위치를 지정할 수 있다. (k=1)
a = np.eye(3, 4, k=1) # 3행 4열
print(a)                 # [[0. 1. 0. 0.][0. 0. 1. 0.][0. 0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
a = np.identity(3)
print(a)                  # [[1. 0. 0.][0. 1. 0.][0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
a = np.full((2,2), 1)  # np.full(shape, fill_value)
print(a)                 # [[1 1][1 1]]

[[1 1]
 [1 1]]


In [36]:
a = np.full((2,2), [1, 2])  # np.full(shape, fill_value)
print(a)                   # [[1 2][1 2]]

[[1 2]
 [1 2]]


In [37]:
a = np.full((2,2), [[1],[2]])  # np.full(shape, fill_value)
print(a)                    # [[1 1][2 2]]

[[1 1]
 [2 2]]


In [38]:
a = np.full((2,2), [[1,2],[3,4]])  # np.full(shape, fill_value)
print(a)                     # [[1 2][3 4]]

[[1 2]
 [3 4]]


In [43]:
a = np.empty(3)
print(a)                    #[1. 1. 1.]

[1. 1. 1.]


In [42]:
a = np.empty((2,3))
print(a)            #[[1. 0. 0.][1. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]


In [46]:
a = np.linspace(0,49)
print(a)               # [0.  1.  2. 3. ... 49.]    

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


In [47]:
a = np.linspace(0,5)
print(a)  # [0. 0.10204082  ...  4.89795918 5.]

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [48]:
# endpoint=False로 설정하면 5가 포함이 안된다.
a = np.linspace(0, 5, endpoint=False)
print(a)            # [0.   0.1  0.2 ..  4.7, 4.8  4.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]


In [49]:
a = np.logspace(1, 50)
print(a)            # [1.e+01 1.e+02 1.e+03,...,1.e+48 1.e+49 1.e+50]

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]


In [50]:
a = np.logspace(1, 50, 10)
print(a)              # [1.00000000e+01 ... 1.00000000e+50]

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


In [52]:
# 기본 사용법
# 0부터 9까지의 숫자 배열 생성
arr = np.arange(10)
print(arr)              # [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [54]:
# 시작 값과 종료 값 설정
arr = np.arange(3, 10)  # 3부터 9까지
print(arr)              # [3 4 5 6 7 8 9]

[3 4 5 6 7 8 9]


In [57]:
# 간격 설정
arr = np.arange(1, 10, 2)  # 1부터 9까지 2씩 증가
print(arr)                 # [1 3 5 7 9]

[1 3 5 7 9]


In [59]:
# 실수 간격 사용
arr = np.arange(0, 1, 0.1)  # 0부터 1까지 0.1씩 증가
print(arr)  # [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [62]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


In [61]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.ones_like(a) # a배열의 shape을 복사한다.
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.empty_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [64]:
a = np.array([[1.,2.,3.],[4.,5.,6.]])
print(a)

b = np.zeros_like(a)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [65]:
# 동일한 난수 결과 발생을 위한 난수 시드 값 고정
np.random.seed(42)

num = np.random.rand(2, 3)
print(num)

# 평균 0, 표준편차 1 구조를 만족하는 3행 3열의 정규분포 매트릭스 빌드
normal_dist_matrix = np.random.randn(3, 3)
print(normal_dist_matrix)   # [[-0.23415337 ... 0.24196227]]


# 1부터 45 미만의 범위에서 무작위 로또 번호 숫자를 닮은 6개 정수 생성
lotto_numbers = np.random.randint(1, 45, size=6)
print(lotto_numbers)     # [39 29 15 43  8 21]


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]
[42 28 16 15 44  3]


In [66]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method

In [68]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers

    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [69]:
np.array?


Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [70]:
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i

In [72]:
a = [1, 2, 3]        # list
b = a
print(b)
print(a is b )        # 메모리 주소 비교 True
b[0] = 7
print(a)               # [7, 2, 3]           
print(b)                # [7, 2, 3]




[1, 2, 3]
True
[7, 2, 3]
[7, 2, 3]


In [73]:

a = [1,2,3]
b = a.copy()
id(a)                 # 133162358434304
id(b)                 # 133162358425280
print(a is b)         # 주소 비교 False
print(a == b)         # 값 비교 True

b[0] = 8
# a는 안바뀐다.
print(a)               # [1, 2, 3]
print(b)               # [8, 2, 3]
print(a is b)          # 메모리 주소 비교  False
print(a == b)          # 값 비교           False

False
True
[1, 2, 3]
[8, 2, 3]
False
False


In [ ]:
a = [[1,2,3]]
print(type(a))           # list

b = a.copy()
print(id(a))              # 133162358428608
print(id(b))              # 133162358989568

print(a is b)             # False
print(a == b)             # True

b[0][0] = 10
print(a[0])               # [10, 2, 3]
print(b[0])               # [10, 2, 3]

<class 'list'>
1733684416256
1733685263872
False
True
[10, 2, 3]
[10, 2, 3]


In [75]:
import copy

a = [[1,2,3]]
# list가 2차원일때 deep copy을 하기 위해서 copy모듈에 있는 
# deepcopy메소드를 사용한다.
b = copy.deepcopy(a) 

print(a[0] is b[0])        # 메모리 주소 False
print(a[0] == b[0])        # 값 True

b[0][0] = 10

print(a[0] is b[0])         # 메모리 주소 False
print(a[0] == b[0])         # 값 False

print(a)                    # [[1, 2, 3]]
print(b)                    # [[10, 2, 3]]

False
True
False
False
[[1, 2, 3]]
[[10, 2, 3]]


In [76]:
a = [1,2,3]
b = a[:]
print(a)                      # [1,2,3]
print(b)                      # [1,2,3]

b[0] = 10
print(a)                      # [1, 2, 3]
print(b)                      # [10, 2, 3]

a = [[1,2,3]]
b = a[:]
print(a is b)                 # False
print(a == b)                 # True

 # 메모리 주소 비교  => 2차원일때 deepcopy 가 발생되지 않음
print(a[0][0] is b[0][0])                    #True
print(a[0][0] == b[0][0])  # 값비교           True


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]
[10, 2, 3]
False
True
True
True


In [77]:
a = b = np.array([1,2,3])
print(a is b)                         # True
print(a == b)                         # [ True  True  True]

a[0] = 100
print(a[0])                           # 100
print(b[0])                           # 100


a = np.array([1,2,3])
b = a.copy()

print(a is b)                           # 메모리 주소 False      
print(a == b)                           # 값 [ True  True  True]

True
[ True  True  True]
100
100
False
[ True  True  True]


In [78]:
import numpy as np

# create a numpy array
numbers = np.array([1, 3, 5, 7, 9])

# access the last element
print(numbers[-1])    # prints 9

# access the second-to-last element
print(numbers[-2])    # prints 7

9
7


In [79]:
import numpy as np

# 3행 3열 구조의 2차원 기본 배열 정의
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 1번 행의 2번 열 데이터 단독 호출 ➔ 값: 6
target_value = arr[1, 2]
print(target_value)  # 출력 결과: 6


6


In [82]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[arr >5]) # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [80]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 불리언 인덱싱: 5보다 큰 데이터만 필터링
bool_mask = arr > 5
print(arr[bool_mask])  # 출력: [6, 7, 8, 9]

[6 7 8 9]


In [81]:
arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6,7],
    [8, 9, 10, 11]
])

axis_ABC = ['A', 'A', 'B', 'C', 'C']

bool_mask = arr[axis_ABC == 'A']
print(arr[bool_mask])  # 출력: [[0,1,2,3], [4,5,6,7]]
                        

[]


In [83]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 팬시 인덱싱: 0번 행과 2번 행만 선택하여 추출
print(arr[[0, 2]])     # 출력: [[1, 2, 3], [7, 8, 9]]

[[1 2 3]
 [7 8 9]]


In [84]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11],
    [12, 13, 14]
])

print(arr[[1, 2]])     # [[3, 4,5], [6, 7, 8]]

print(arr[[-1, -2]])    # [[12, 13, 14], [9, 10, 11]]

[[3 4 5]
 [6 7 8]]
[[12 13 14]
 [ 9 10 11]]


In [102]:
a = np.arange(24).reshape(2,3,4) # 3차원(2층(면, 공간), 3행, 4열)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [130]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원을 2차원으로 가져온다.)
a[0]

# ```
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])
# ```

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
# fancy indexing은 원래 3차원 그대로 가져온다.
a[[0]]

# ```
# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])
# ```

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [103]:
a[0]=a[0, :, :]=a[0,...]
print(a[0])  # indexing 기법
print(a[0, :, :]) # slicing 기법
print(a[0,...])  # ellipsis 기법(생략기법)

# #```
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
#  ```

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [101]:
type(...)    # ellipsis

ellipsis

In [126]:
a[[0], :, :] # b[[0]]은  b[[0], :, :]의 단축 표현이다.
# ```
# array([[[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]]])
#  ```

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [110]:
a[0, :, 1]        # array([1, 5, 9])


array([1, 5, 9])

In [107]:
a[[0],:, [1]]     # array([[1, 5, 9]])

array([[1, 5, 9]])

In [108]:
# 숫자 1, 5, 9, 3, 7, 11가져오기
print(a[0, :, 1])              # [1 5 9]

[1 5 9]


In [109]:
a[[0], :, [1]]                 # array([[1, 5, 9]])

array([[1, 5, 9]])

In [116]:
# 숫자 1,5,9,3,7,11 가져오기
a[[0], :, [1,3]]

# ```
# array([[ 1,  5,  9],
#        [ 3,  7, 11]])
       
#  ```

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [119]:
# 숫자 4,5,6,7,16,17,18,19 가져오기
a[:, 1, :]

# ```
# array([[ 4,  5,  6,  7],
#        [16, 17, 18, 19]])
# ```

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [135]:
a = np.arange(24).reshape(2,3,4) 
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [136]:
b = a[:, [1], :]
b.shape

(2, 1, 4)

In [138]:
b = a[[1], :, :]
b.shape

(1, 3, 4)

In [139]:
a[[1]]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [132]:
b = np.arange(32).reshape(2, 4, 4)   # 3차원으로 다시 만들기
print(b.shape)                        # (2, 4, 4) 확인
b[:, [1], :]                          # 이제 정상 작동

(2, 4, 4)


array([[[ 4,  5,  6,  7]],

       [[20, 21, 22, 23]]])

In [137]:
b[:, [1], :]

# ```
# array([[[ 4,  5,  6,  7]],

#        [[16, 17, 18, 19]]])
#  ```

IndexError: index 1 is out of bounds for axis 1 with size 1

In [114]:
# # 숫자 3,7,11,15,19,23 가져오기
a[:, :, 3]

# ```
# array([[ 3,  7, 11],
#        [15, 19, 23]])
#  ```

array([[ 3,  7, 11],
       [15, 19, 23]])

In [113]:
a[:, :, [3]]

# ```
# array([[[ 3],
#         [ 7],
#         [11]],

#        [[15],
#         [19],
#         [23]]])
# ```  

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [133]:
a[:, :, -1]

# ```
# array([[ 3,  7, 11],
#        [15, 19, 23]])
#  ```

array([[ 3,  7, 11],
       [15, 19, 23]])

In [134]:
a[..., -1]

# ```
# array([[ 3,  7, 11],
#        [15, 19, 23]])
#   ```

array([[ 3,  7, 11],
       [15, 19, 23]])

In [123]:
a[..., 3]

# ```
# array([[ 3,  7, 11],
#        [15, 19, 23]])
#  ```

array([[ 3,  7, 11],
       [15, 19, 23]])

In [124]:
a[..., 3]

# ```
# array([[ 3,  7, 11],
#        [15, 19, 23]])
#  ```

array([[ 3,  7, 11],
       [15, 19, 23]])

In [125]:
a[..., 3:4]

# ```
# array([[[ 3],
#         [ 7],
#         [11]],

#        [[15],
#         [19],
#         [23]]])
#    ```

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [140]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [141]:
np.set_printoptions(edgeitems=6)
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [142]:
# out에 나오는 ...은 단순히 줄임표현이다.
np.arange(10000)

# ```
# array([   0,    1,    2, ..., 9997, 9998, 9999])
# ```

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [143]:
# ... 양쪽으로 출력 갯수 지정
np.set_printoptions(edgeitems=6)

np.arange(10000)

# ```
# array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
#        9998, 9999])
# ```

array([   0,    1,    2,    3,    4,    5, ..., 9994, 9995, 9996, 9997,
       9998, 9999], shape=(10000,))

In [145]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [144]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')     

[1 2 3 4]
메모리 공유 확인:: False


In [146]:
arr = np.array([[1, 2], [3, 4]])

dap = arr.flatten()
print(dap)                      # 출력 : [1 2 3 4]


# 메모리 공유 확인:: False
print(f'메모리 공유 확인:: {np.shares_memory(arr, dap)}')     
print(f'{(arr is dap)}')     

[1 2 3 4]
메모리 공유 확인:: False
False


In [154]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d ,arr_2d)}') 


# 질문: "두 배열이 같은 숫자 창고를 쓰고 있냐?"
# → 응, 같은 창고 씀 (그래서 True)

메모리 공유 확인:: True


In [ ]:
# 1차원 12개 원소 배열을 3행 4열 2차원 배열로 변경
arr_1d = np.arange(12)
arr_2d = arr_1d.reshape(3, 4)

# 메모리 공유 확인:: True
print(f' {(arr_1d is arr_2d)}') 

# 질문: "두 개가 완전히 똑같은 상자(객체) 그 자체냐?"

# arr_1d랑 arr_2d는:

# 안에 든 숫자 창고는 같음 (shares_memory = True)
# 근데 상자 자체(껍데기)는 다름 — shape 정보, 타입 정보 등을 담은 "포장지"가 각각 따로 있음

 False


## 무엇을 비교	결과
shares_memory	안에 든 **값(데이터)**이 같은 자리를 쓰냐	True


is	**객체 자체(포장지)**가 완전히 동일하냐	False

In [ ]:

# 행의 크기는 2로 지정하고, 열의 크기는 자동 계산(-1)하여 배치
arr_auto = arr_1d.reshape(2, -1)  # 결과적으로 2행 6열로 자동 변환됨
# 2줄로 만들 건데, 칸 수는 니가 계산해" → 12개 ÷ 2줄 = 6칸으로 자동 계산
# 메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_1d,arr_auto)}')
# 이것도 shares_memory → True (역시 창고 공유, 창문 모양만 다름)

메모리 공유 확인:: True


In [156]:

arr_2d = arr_1d.reshape(3, 4)
arr_line= np.ravel(arr_2d)

# [ 0  1  2  3  4  5  6  7  8  9 10 11]
print(arr_line)
#메모리 공유 확인:: True
print(f'메모리 공유 확인:: {np.shares_memory(arr_2d, arr_line)}')
# 3행 4열짜리를 다시 1차원으로 쭉 폄. 이것도 shares_memory → True (여전히 같은 창고)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
메모리 공유 확인:: True


### 핵심 정리

함수	 /   하는    /    일	 /   메모리

reshape() /	모양     /  바꾸기	/공유 (창문만 다름)

ravel()	  /  1차원으로  / 펴기	/공유 (창문만 다름)

flatten()	/ 1차원으로 /  펴기	/분리 (새 창고)


한 줄 요약: reshape도 ravel도 원본이랑 같은 숫자 창고를 쓰는 거라서, 어느 쪽 값을 바꿔도 서로 다 같이 바뀜.

 flatten만 예외적으로 완전히 딴 살림(새 창고)을 차림.


-----------------------------------------------------------------------

### 한 줄 요약 전체 정리

기능	/하는 일

vstack , hstack , concatenate/	종이 이어붙이기 (차원 그대로)

stack/	종이 포개서 쌓기 (차원 하나 늘어남)

split , hsplit , vsplit/	피자 자르듯 나누기 (합치기의 반대)

### 합치기 — vstack, hstack, concatenate

비유: 레고 블록 두 개를 이어 붙이는 것

python
a = [[1, 2, 3]]
b = [[4, 5, 6]]

세로로 붙이기 (vstack, axis=0)

[1 2 3]
[4 5 6]     ← 위아래로 쌓음 (줄이 늘어남)

가로로 붙이기 (hstack, axis=1)

[1 2 3 4 5 6]     ← 옆으로 이어 붙임 (칸이 늘어남)

concatenate(axis=0) = vstack이랑 똑같음, concatenate(axis=1) = hstack이랑 똑같음. 그냥 함수 이름만 다른 거임.

1차원일 때만 조심할 것: 1차원 배열([1,2,3])은 "줄"이라는 개념 자체가 없어서 axis=1(가로 방향)로 붙이려고 하면 에러 남. 그래서 hstack은 되는데 concatenate(axis=1)은 에러 나는 거임.

### stack — "합치는" 게 아니라 "새로 쌓는" 것

여기가 제일 헷갈리는 부분. concatenate랑 stack은 완전히 다른 개념임.

concatenate = 종이 두 장을 이어붙여서 한 장의 큰 종이를 만듦 (여전히 종이는 1장, 그냥 커짐)
stack = 종이 두 장을 포개서 위아래로 쌓음 (종이가 2장인 채로, 층이 하나 새로 생김)


핵심: concatenate는 종이가 계속 1장, stack은 종이가 여러 장으로 쌓임(차원이 늘어남).

stack의 axis는 "어느 방향으로 층을 쌓을지"를 정하는 거임:

axis=0 → 앞에 새 층을 만듦 → shape이 (2, 3, 2) (2장이 앞에 붙음)
axis=1 → 중간에 층을 끼워 넣음 → shape이 (3, 2, 2) (줄마다 짝지어서 쌓음)


### split — 자르는 것 (합치기의 반대)

비유: 피자를 몇 조각으로 써는 것

python
a = np.arange(12).reshape(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

세로로 자르기 (np.split(a, 2, axis=1)) → "칸을 2묶음으로 나눠"

x = [[0,1],[4,5],[8,9]]      ← 왼쪽 반
y = [[2,3],[6,7],[10,11]]    ← 오른쪽 반
hsplit = 가로 방향으로 자르기 (axis=1이랑 같음)
vsplit = 세로 방향으로 자르기 (axis=0이랑 같음)
숫자 대신 (2,4)처럼 튜플을 넣으면 "2번째 자리에서 한 번, 4번째 자리에서 한 번" 이렇게 특정 위치에서 자름 (균등하게 안 나눠도 됨)

In [161]:
a = np.array([[1, 2, 3]])
print(f'a={a}')                                # a=[[1 2 3]]

b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]



a=[[1 2 3]]
b=[[4 5 6]]


In [162]:
print(np.r_[a,b]) # [[1 2 3][4 5 6]]

[[1 2 3]
 [4 5 6]]


In [163]:
v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')       # v_row:: [[1 2 3][4 5 6]]

v_row:: [[1 2 3]
 [4 5 6]]


In [164]:
concat_row = np.concatenate((a, b), axis=0)    # axis = 0
print(f'concat_row:: {concat_row}')            # concat_row:: [[1 2 3][4 5 6]]

concat_row:: [[1 2 3]
 [4 5 6]]


-------------------------------------------------------------------------------------

In [168]:
a = np.array([[1, 2, 3]])
print(f'a={a}')       # a=[[1 2 3]]


a=[[1 2 3]]


In [169]:
b = np.array([[4, 5, 6]])
print(f'b={b}')                                # b=[[4 5 6]]


b=[[4 5 6]]


In [170]:
print(np.c_[a,b])                              # [[1 2 3 4 5 6]]

[[1 2 3 4 5 6]]


In [171]:
h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [[1 2 3 4 5 6]]

h_col:: [[1 2 3 4 5 6]]


In [172]:

concat_col = np.concatenate((a, b), axis=1)    # axis = 1
print(f'concat_col:: {concat_col}')            # concat_col:: [[1 2 3 4 5 6]]

concat_col:: [[1 2 3 4 5 6]]


-------------------------------------------------------------------------------------

1차원

In [173]:
a = np.array([1, 2, 3])
print(f'a={a}')           # a=[1 2 3]      

a=[1 2 3]


In [174]:
b = np.array([4, 5, 6])
print(f'b={b}')           # b=[4 5 6]


b=[4 5 6]


In [175]:
print(np.r_[a,b])


[1 2 3 4 5 6]


In [185]:

v_row = np.vstack([a,b])
print(f'v_row:: {v_row}')     # v_row:: [[1 2 3]
                                    #[4 5 6]]

v_row:: [[1 2 3]
 [4 5 6]]


In [176]:

h_row = np.vstack([a,b])
print(f'h_row:: {h_row}')     # h_row:: [[1 2 3][4 5 6]]

h_row:: [[1 2 3]
 [4 5 6]]


In [177]:

concat_row = np.concatenate((a, b), axis=0)  # axis = 0
print(f'concat_row:: {concat_row}') # concat_row:: [1 2 3 4 5 6]

concat_row:: [1 2 3 4 5 6]


------------------------------------------------------------------------------------

In [178]:
a = np.array([1, 2, 3])
print(f'a={a}')                                # a=[1 2 3]

a=[1 2 3]


In [179]:

b = np.array([4, 5, 6])
print(f'b={b}')                                # b=[4 5 6]

b=[4 5 6]


In [180]:

print(np.c_[a,b])                              # [[1 4][2 5][3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [181]:

h_col = np.hstack([a,b])
print(f'h_col:: {h_col}')                      # h_col:: [1 2 3 4 5 6]

h_col:: [1 2 3 4 5 6]


In [183]:
# AxisError: axis 1 is out of bounds for array of dimension 1
concat_col = np.concatenate((a, b), axis=1)    # axis = 1

AxisError: axis 1 is out of bounds for array of dimension 1

---------------------------------------------------------------------------------------

concatenate는 axis 방향에 그대로 합쳐준다

※  stack는 axis 방향에 새로운 차원을 만들어 합쳐준다.

In [186]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [187]:
x, y = np.split(a, 2, axis = 1)
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [189]:
# 2차원이면 3차원으로 증가한다.
b = np.stack((x,y), axis = 0)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)


(2, 3, 2)
[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[ 2  3]
  [ 6  7]
  [10 11]]]


In [190]:
b = np.stack((x,y), axis = 1)
print(b.shape) # 2차원(m, n) => 3차원(2, m, n)
print(b)

(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [191]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)


(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [192]:
c = np.concatenate((x, y), axis=0)
print(c.shape)
print(c)

(6, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [ 2  3]
 [ 6  7]
 [10 11]]


In [193]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [194]:
c = np.concatenate((x, y), axis=1)
print(c.shape)
print(c)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


-------------------------------------------------------------------------------------

In [205]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))

print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [195]:
x = np.arange(18)
print(f'x::{x}')


x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [196]:
x = x.reshape(-1, 6)
print(f'x::{x}')

x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [197]:
print(np.hsplit(x, 3))
print(np.hsplit(x, (2,4)))


[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [198]:

print(np.split(x, 3, axis=1))
print(np.split(x, (2, 4), axis=1))


[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]])]


In [199]:

# ```
# [array([[ 0,  1],
#        [ 6,  7],
#        [12, 13]]), array([[ 2,  3],
#        [ 8,  9],
#        [14, 15]]), array([[ 4,  5],
#        [10, 11],
#        [16, 17]])]
#  ```      

In [206]:
x = np.arange(18)
print(f'x::{x}')

x = x.reshape(-1, 6)
print(f'x::{x}')

print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

print(np.split(x, 3, axis=0))
print(np.split(x, (1, 2), axis=0))

x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [200]:
x = np.arange(18)
print(f'x::{x}')


x::[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [201]:
x = x.reshape(-1, 6)
print(f'x::{x}')

x::[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [202]:
print(np.vsplit(x, 3))
print(np.vsplit(x, (1,2)))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [203]:
print(np.split(x, 3, axis=0))
print(np.split(x, (1, 2), axis=0))

[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]


In [204]:
# [array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17]])]

--------------------------------------------------------------

### 차원 확장

In [ ]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# 행 방향(axis 0) 확장 -> shape: (1, 3)
row_vec = arr[np.newaxis, :]

# 열 방향(axis 1) 확장 -> shape: (3, 1)
col_vec = arr[:, np.newaxis]

print("행벡터:\n", row_vec)
print("열벡터:\n", col_vec)

# ```
# 행벡터:
#  [[1 2 3]]
# 열벡터:
#  [[1]
#  [2]
#  [3]]
#  ```
 

행벡터:
 [[1 2 3]]
열벡터:
 [[1]
 [2]
 [3]]


In [210]:
print( np.newaxis is None)
# 열 추가

a = np.arange(12).reshape(3,4)
print(a)

# ```
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]
#  ```



True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [211]:
b = a[ :, :, None ]
print(b.shape) # (3, 4, 1)
print(b)

# ```
# (3, 4, 1)
# [[[ 0]
#   [ 1]
#   [ 2]
#   [ 3]]

#  [[ 4]
#   [ 5]
#   [ 6]
#   [ 7]]

#  [[ 8]
#   [ 9]
#   [10]
#   [11]]]
  
#   ```

(3, 4, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [212]:
import numpy as np

arr = np.array([1, 2, 3]) # shape: (3,)

# axis=0 위치에 차원 추가 -> shape: (1, 3)
e0 = np.expand_dims(arr, axis=0)

# axis=1 위치에 차원 추가 -> shape: (3, 1)
e1 = np.expand_dims(arr, axis=1)

print("e0.shape:", e0.shape) # (1, 3)
print("e1.shape:", e1.shape) # (3, 1)

e0.shape: (1, 3)
e1.shape: (3, 1)


----------------------------------------------------------------------------

### 차원 축소 

In [213]:
import numpy as np

# shape: (1, 3, 1) 인 3차원 배열
arr_3d = np.array([[[1], [2], [3]]])

# 크기가 1인 모든 차원 축소 -> shape: (3,)
squeezed = np.squeeze(arr_3d)

print("원래 shape:", arr_3d.shape) # (1, 3, 1)
print("축소 후 shape:", squeezed.shape) # (3,)
print("결과:", squeezed) # [1 2 3]

원래 shape: (1, 3, 1)
축소 후 shape: (3,)
결과: [1 2 3]


In [214]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]]) # shape: (2, 2)

# 모두 1차원 배열 [1, 2, 3, 4] (shape: (4,))로 변환
r_arr = matrix.ravel()
f_arr = matrix.flatten()
re_arr = matrix.reshape(-1)

print("1차원 평탄화 결과:", r_arr) # [1 2 3 4]

1차원 평탄화 결과: [1 2 3 4]


---------------------------------------------------------------------

### 벡터화 연산과 브로드캐스팅 (핵심 구간)

강의 목표: 반복문(for) 없는 코딩의 핵심인 '벡터화 연산'과 '브로드캐스팅'의 원리를 마스터한다.

## 3.1 **유니버설 함수 (ufunc)**: 사칙연산, 제곱근(`sqrt`), 지수/로그(`exp`, `log`)의 요소별(Element-wise) 고속 연산

유니버설 함수(Universal Functions, 줄여서 ufunc)는 NumPy의 가장 핵심적인 기능 중 하나로, **`ndarray` 배열의 모든 원소(element)에 대해 빠르게 연산을 수행하는 함수**를 의미이다.

**1) ufunc의 핵심 특징**

- **원소별 연산 (Element-wise Operations)**
    
    파이썬의 기본 반복문(`for` 문)을 작성하지 않아도, 배열의 각 원소에 동시에 함수가 적용된다.
    
- **C언어 기반의 속도 (Fast Speed)**
    
    내부적으로 C언어로 구현되어 있어 순수한 파이썬 코드로 반복문을 돌리는 것보다 연산 속도가 훨씬 빠르다.
    
- **브로드캐스팅 지원 (Broadcasting)**
    
    모양이 완전히 같지 않은 배열끼리도 일정한 규칙(브로드캐스팅)에 따라 연산을 맞춰서 수행해 다.
    
    **2) ufunc의 분류**
    
    ufunc는 **입력받는 배열의 개수**에 따라 크게 두 가지로 나뉩니다.
    
    ① 단항 유니버설 함수 (Unary ufunc)
    
    - **입력:** 1개의 배열
    - **기능:** 배열의 각 원소에 단독으로 연산을 수행합니다.
    - **주요 함수:**
        - `np.abs()`: 절대값
        - `np.sqrt()`: 제곱근
        - `np.exp()`, `np.log()`: 지수 및 로그
        - `np.sin()`, `np.cos()`: 삼각함수
        - `np.ceil()`, `np.floor()`: 올림과 내림
    
    ② 이항 유니버설 함수 (Binary ufunc)
    
    - **입력:** 2개의 배열 (또는 배열과 스칼라)
    - **기능:** 두 배열의 같은 위치에 있는 원소끼리 짝을 지어 연산을 수행합니다.
    - **주요 함수:**
        - `np.add()`, `np.subtract()`: 덧셈, 뺄셈 (산술 연산)
        - `np.maximum()`, `np.minimum()`: 두 배열 중 크거나 작은 값 선택
        - `np.greater()`, `np.equal()`: 원소별 대소/등가 비교 연산
        - `np.copysign()`: 한 배열의 부호를 다른 배열에 복사
    
    3) 왜 ufunc를 써야 할까요? (파이썬 리스트 vs ufunc 비교)
    
    예를 들어 배열의 모든 원소에 절대값을 취해야 할 때의 차이 이다.

In [215]:
import numpy as np

arr = [-2.1, 0, 1.5, 3.7]

# 1. 일반 파이썬 반복문 (느림)
result_python = [abs(x) for x in arr]

# 2. NumPy ufunc 사용 (매우 빠르고 간결함)
result_ufunc = np.abs(arr)

- **코드의 간결성:** 반복문 없이 단 한 줄로 처리가 가능합니다.
- **성능:** 데이터의 개수가 수백만 개 이상으로 늘어날수록 ufunc의 처리 속도가 수십~수백 배 이상 빠릅니다.

In [217]:
#  1개의 배열에 대한 ufunc (Unary Universal Functions)


import numpy as np

# 입력 데이터
x = np.array([-2.1, 0, 1.5, 3.7])

# ==============================================================================
# 1. 원소별 산술 연산 (element-wise arithmetic computation)
# ==============================================================================
print(np.abs(x))        # 절대값 계산 -> 출력: [2.1 0.  1.5 3.7]
print(np.fabs(x))       # 절대값 계산 (부동소수점 전용) -> 출력: [2.1 0.  1.5 3.7]

print(np.ceil(x))       # 올림 -> 출력: [-2.  0.  2.  4.]
print(np.floor(x))      # 내림 -> 출력: [-3.  0.  1.  3.]

print(np.modf(x))       # 소수 부분과 정수 부분 분리 -> 출력: (array([-0.1,  0. ,  0.5,  0.7]), array([-2.,  0.,  1.,  3.]))
print(np.rint(x))       # 가장 가까운 정수로 반올림 -> 출력: [-2.  0.  2.  4.]

print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
print(np.log2(x))       # 로그(log2) -> 출력: [       nan       -inf 0.5849625  1.88752538]
print(np.log1p(x))      # log(1 + x) 계산 -> 출력: [       nan 0.         0.91629073 1.54756251]

print(np.exp(x))        # 지수함수 (e^x) -> 출력: [ 0.12245643  1.          4.48168907 40.44730436]
print(np.sqrt(x))       # 제곱근 -> 출력: [       nan 0.         1.22474487 1.92353841]
print(np.square(x))     # 제곱 (x^2) -> 출력: [ 4.41  0.    2.25 13.69]


# ==============================================================================
# 2. 불리언 배열 반환 (returns boolean array)
# ==============================================================================
print(np.isnan(x))       # NaN(결측치) 여부 검사 -> 출력: [False False False False]
print(np.isfinite(x))    # 유효한 숫자(유한수) 여부 검사 -> 출력: [ True  True  True  True]
print(np.logical_not(x)) # 논리 부정 (Not) -> 출력: [False  True False False]


# ==============================================================================
# 3. 부호 반환 (returns the sign of each element)
# ==============================================================================
print(np.sign(x))       # 각 원소의 부호 (양수:1, 0:0, 음수:-1) -> 출력: [-1.  0.  1.  1.]


# ==============================================================================
# 4. 삼각함수 및 역삼각함수 (regular or inverse trigonometric functions)
# ==============================================================================
print(np.sin(x))        # 사인 (sin) -> 출력: [-0.86320937  0.          0.99749499 -0.52983614]
print(np.cos(x))        # 코사인 (cos) -> 출력: [-0.5048461   1.          0.0707372  -0.84810002]
print(np.tan(x))        # 탄젠트 (tan) -> 출력: [ 1.7098674   0.         14.10141995  0.62473215]

print(np.arcsin(x))     # 아크사인 (arcsin) -> 출력: [       nan 0.                nan        nan]
print(np.arccos(x))     # 아크코사인 (arccos) -> 출력: [       nan 1.57079633        nan        nan]
print(np.arctan(x))     # 아크탄젠트 (arctan) -> 출력: [-1.12586589  0.          0.98279372  1.30658742]

[2.1 0.  1.5 3.7]
[2.1 0.  1.5 3.7]
[-2.  0.  2.  4.]
[-3.  0.  1.  3.]
(array([-0.1,  0. ,  0.5,  0.7]), array([-2.,  0.,  1.,  3.]))
[-2.  0.  2.  4.]
[       nan       -inf 0.40546511 1.30833282]
[       nan       -inf 0.17609126 0.56820172]
[       nan       -inf 0.5849625  1.88752527]
[       nan 0.         0.91629073 1.54756251]
[ 0.12245643  1.          4.48168907 40.44730436]
[       nan 0.         1.22474487 1.92353841]
[ 4.41  0.    2.25 13.69]
[False False False False]
[ True  True  True  True]
[False  True False False]
[-1.  0.  1.  1.]
[-0.86320937  0.          0.99749499 -0.52983614]
[-0.5048461   1.          0.0707372  -0.84810003]
[ 1.70984654  0.         14.10141995  0.62473308]
[nan  0. nan nan]
[       nan 1.57079633        nan        nan]
[-1.12637712  0.          0.98279372  1.3068326 ]


C:\Users\playdata2\AppData\Local\Temp\ipykernel_28068\3315418919.py:21: RuntimeWarning: divide by zero encountered in log
  print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_28068\3315418919.py:21: RuntimeWarning: invalid value encountered in log
  print(np.log(x))        # 자연로그(ln) -> 출력: [       nan       -inf 0.40546511 1.30833282]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_28068\3315418919.py:22: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_28068\3315418919.py:22: RuntimeWarning: invalid value encountered in log10
  print(np.log10(x))      # 상용로그(log10) -> 출력: [       nan       -inf 0.17609126 0.56820172]
C:\Users\playdata2\AppData\Local\Temp\ipykernel_28068\3315418919.py:23: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(x))  

In [218]:
# 2개의 배열 간 ufunc (Binary Universal Functions)
import numpy as np

# 입력 데이터
m = np.array([0, 1, 2, 3])
n = np.array([1, 1, 2, 2])

# ==============================================================================
# 1. 두 배열 간 원소별 산술 연산 (element-wise arithmetic operations b/w arrays)
# ==============================================================================
print(np.add(m, n))          # 덧셈 (m + n) -> 출력: [1 2 4 5]
print(np.subtract(m, n))     # 뺄셈 (m - n) -> 출력: [-1  0  0  1]
print(np.multiply(m, n))     # 곱셈 (m * n) -> 출력: [0 1 4 6]
print(np.divide(m, n))       # 나눗셈 (m / n) -> 출력: [0.  1.  1.  1.5]
print(np.floor_divide(m, n)) # 몫 나눗셈 (m // n) -> 출력: [0 1 1 1]
print(np.mod(m, n))          # 나머지 연산 (m % n) -> 출력: [0 0 0 1]
print(np.power(m, n))        # 거듭제곱 (m ** n) -> 출력: [0 1 4 9]

print(np.maximum(m, n))      # 두 배열 중 큰 값 선택 -> 출력: [1 1 2 3]
print(np.fmax(m, n))         # 큰 값 선택 (NaN 무시) -> 출력: [1 1 2 3]
print(np.minimum(m, n))      # 두 배열 중 작은 값 선택 -> 출력: [0 1 2 2]
print(np.fmin(m, n))         # 작은 값 선택 (NaN 무시) -> 출력: [0 1 2 2]


# ==============================================================================
# 2. 두 배열 간 비교 연산 (comparison operations b/w arrays)
# ==============================================================================
print(np.greater(m, n))       # m > n -> 출력: [False False False  True]
print(np.greater_equal(m, n)) # m >= n -> 출력: [False  True  True  True]
print(np.less(m, n))          # m < n -> 출력: [ True False False False]
print(np.less_equal(m, n))    # m <= n -> 출력: [ True  True  True False]
print(np.equal(m, n))         # m == n -> 출력: [False  True  True False]
print(np.not_equal(m, n))     # m != n -> 출력: [ True False False  True]


# ==============================================================================
# 3. 부호 복사 (copy sign of values)
# ==============================================================================
print(np.copysign(m, n))      # n의 부호를 m의 크기에 적용 -> 출력: [0. 1. 2. 3.]
print(np.copysign(n, m))      # m의 부호를 n의 크기에 적용 -> 출력: [1. 1. 2. 2.]

[1 2 4 5]
[-1  0  0  1]
[0 1 4 6]
[0.  1.  1.  1.5]
[0 1 1 1]
[0 0 0 1]
[0 1 4 9]
[1 1 2 3]
[1 1 2 3]
[0 1 2 2]
[0 1 2 2]
[False False False  True]
[False  True  True  True]
[ True False False False]
[ True  True  True False]
[False  True  True False]
[ True False False  True]
[0. 1. 2. 3.]
[1. 1. 2. 2.]


In [219]:
import numpy as np

# ==============================================================================
# 테스트용 입력 데이터 예시
# ==============================================================================
c = np.array([[1, 2], 
              [3, 4]])

d = np.array([[1, np.nan], 
              [3, 4]])  # NaN(결측치) 포함 배열

f = np.array([[1, 2], 
              [3, 4]])

g = np.array([1, 2, 4, 7, 11])

h = np.array([[1, 3, 6], 
              [2, 5, 9]])


# ==============================================================================
# 1. 배열 원소 간 곱 계산 범용 함수 (product ufuncs)
# ==============================================================================
print(np.prod(c, axis=0))      # 세로 방향(열별) 원소 곱 -> 출력: [3 8]
print(np.prod(c, axis=1))      # 가로 방향(행별) 원소 곱 -> 출력: [2 12]

print(np.nanprod(d, axis=0))   # NaN을 1로 무시하고 세로 곱 -> 출력: [3. 4.]
print(np.nanprod(d, axis=1))   # NaN을 1로 무시하고 가로 곱 -> 출력: [1. 12.]

print(np.cumprod(f, axis=0))   # 세로 방향 누적 곱 -> 출력: [[1 2], [3 8]]
print(np.cumprod(f, axis=1))   # 가로 방향 누적 곱 -> 출력: [[1 2], [3 12]]


# ==============================================================================
# 2. 배열 원소 간 합 계산 범용 함수 (sum ufuncs)
# ==============================================================================
print(np.sum(c, axis=0))       # 세로 방향(열별) 원소 합 -> 출력: [4 6]
print(np.sum(c, axis=1))       # 가로 방향(행별) 원소 합 -> 출력: [3 7]

print(np.nansum(d, axis=0))    # NaN을 0으로 무시하고 세로 합 -> 출력: [4. 4.]
print(np.nansum(d, axis=1))    # NaN을 0으로 무시하고 가로 합 -> 출력: [1. 7.]

print(np.cumsum(f, axis=0))    # 세로 방향 누적 합 -> 출력: [[1 2], [4 6]]
print(np.cumsum(f, axis=1))    # 가로 방향 누적 합 -> 출력: [[1 3], [3 7]]


# ==============================================================================
# 3. 배열 원소 간 차분 계산 범용 함수 (difference ufuncs)
# ==============================================================================
print(np.diff(g))              # 인접한 원소 간의 차이 (out[i] = g[i+1] - g[i]) -> 출력: [1 2 3 4]
print(np.diff(h, axis=0))      # 세로 방향(행 간) 차분 -> 출력: [[1 2 3]]
print(np.diff(h, n=2, axis=1)) # 가로 방향으로 2번 연속 차분 수행 -> 출력: [[1], [1]]

print(np.ediff1d(g))           # 1차원으로 펼쳐서 인접 원소 차분 -> 출력: [1 2 3 4]
print(np.ediff1d(h, to_begin=np.array([-100, -99]), to_end=np.array([99, 100]))) 
# 차분 결과 앞(to_begin)과 뒤(to_end)에 지정한 배열 값을 추가
# -> 출력: [-100  -99    2    3   -4    3    4   99  100]


# ==============================================================================
# 4. 배열 원소 간 기울기 계산 범용 함수 (gradient ufuncs)
# ==============================================================================
print(np.gradient(g))          # 중앙 차분법을 이용한 경사도/기울기 계산 -> 출력: [1.  1.5 2.5 3.5 4. ]
print(np.gradient(g, 2))       # 간격(dx)을 2로 지정하여 기울기 계산 -> 출력: [0.5  0.75 1.25 1.75 2.  ]
print(np.gradient(g, edge_order=2)) # 경계선(양 끝)의 정확도를 2차 정확도로 높여 계산 -> 출력: [0.5 1.5 2.5 3.5 4.5]

print(np.gradient(h, axis=0))   # 2차원 배열의 세로 방향(axis=0) 경사도 계산 -> 출력: [[1. 2. 3.], [1. 2. 3.]]
print(np.gradient(h, axis=1))   # 2차원 배열의 가로 방향(axis=1) 경사도 계산 -> 출력: [[2. 2.5 3.], [3. 3.5 4.]]

[3 8]
[ 2 12]
[3. 4.]
[ 1. 12.]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
[4 6]
[3 7]
[4. 4.]
[1. 7.]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]
[1 2 3 4]
[[1 2 3]]
[[1]
 [1]]
[1 2 3 4]
[-100  -99    2    3   -4    3    4   99  100]
[1.  1.5 2.5 3.5 4. ]
[0.5  0.75 1.25 1.75 2.  ]
[0.5 1.5 2.5 3.5 4.5]
[[1. 2. 3.]
 [1. 2. 3.]]
[[2.  2.5 3. ]
 [3.  3.5 4. ]]


## 3.2 **브로드캐스팅 (Broadcasting) 규칙**: 서로 크기가 다른 배열 간의 연산이 가능해지는 마법 같은 원리와 조건

브로드캐스팅(Broadcasting)은 NumPy에서 **모양(Shape)이 서로 다른 배열끼리 연산(덧셈, 뺄셈, 곱셈 등)을 가능하게 만들어주는 핵심 기능이**다.

원래 배열 연산은 크기와 모양이 완벽히 같아야 하지만, NumPy는 특정 조건이 맞으면 작은 배열을 자동으로 큰 배열의 모양에 맞춰 확장(복사)하여 연산을 수행한다.

### **3.2.1  브로드캐스팅의 규칙 (Broadcasting Rules)**

두 배열 A와 B가 연산 가능하려면, **뒤쪽 차원(가장 오른쪽 축)부터 비교**하여 다음 **두 조건 중 하나**를 만족해야  한다.
① **두 차원의 크기가 같다.**
②  **둘 중 하나의 차원 크기가 1이다.** (스칼라도 크기가 1인 차원으로 취급됨)

💡 **비교 예시:**

- `Shape (4, 3)` 과 `Shape (3,)`
$\rightarrow$ 뒤쪽 차원부터 비교: `3 == 3` (같음) / 앞 차원은 1로 간주되어 연산 가능!
- `Shape (4, 3)` 과 `Shape (4,)`
$\rightarrow$ 뒤쪽 차원 비교: `3 != 4` (다르고 1도 아님) $\rightarrow$ **연산 불가능 (Error)**



### 3.2.2 브로드캐스팅 대표 예시 3가지

① 스칼라 + 1차원 배열 (Scalar + 1D Array)

단일 숫자(스칼라)가 배열의 모든 원소에 확장되어 더해진다.

```markdown
array은 scalar와 연산하면 elementwise로 계산한다.  
( elementwise : 원소별로 각각 계산이 된다.)
```

In [220]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr + 10)  # 출력: [11 12 13]

[11 12 13]


② 2차원 배열 + 1차원 배열 (2D Array + 1D Array)

행렬의 각 행에 동일한 1차원 배열이 반복적으로 더해진다.

In [221]:
import numpy as np

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])  # shape: (2, 3)
row_vec = np.array([10, 20, 30]) # shape: (3,)

print(matrix + row_vec)
# 출력:
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


③ 열벡터 + 행벡터 (Column Vector + Row Vector)

`(3, 1)`과 `(1, 3)` 크기의 두 벡터가 각각 행과 열 방향으로 모두 확장되어 `(3, 3)` 행렬 결과를 만다.

In [222]:
import numpy as np

col_vec = np.array([[1], 
                    [2], 
                    [3]])        # shape: (3, 1)
row_vec = np.array([10, 20, 30]) # shape: (3,) -> (1, 3)으로 브로드캐스팅

print(col_vec + row_vec)
# 출력:
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]

[[11 21 31]
 [12 22 32]
 [13 23 33]]


### 3.2.3 브로드캐스팅의 장점

**① 메모리 효율성:** 데이터를 실제로 메모리에 복사하여 늘리지 않고, 연산 시점에 가상으로 맞춰 처리하므로 **메모리를 거의 차지하지 않는다.**

**② 연산 속도:** 반복문(`for` 문) 없이 C언어 수준에서 한 번에 연산하므로 **속도가 훨씬 빠릅니다.**

**③ 코드의 간결성:** 데이터 형상을 맞추기 위한 부가적인 코드가 줄어들어 **가독성이 좋아집니다.**

3.2.4  브로드캐스팅의 다양한 모양

In [223]:
import numpy as np

# 1. Shape (4,) 크기의 1차원 배열 생성
arr = np.array([1, 2, 3, 4])

# 2. 스칼라(단일 값) 정의
scalar = 1

# 3. 배열과 스칼라 간의 덧셈 연산 (브로드캐스팅 발생)
#    스칼라 값 '1'이 배열의 크기인 (4,)에 맞게 [1, 1, 1, 1]로 확장되어 각 원소별로 더해집니다.
result = arr + scalar

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(arr)         # 입력 배열 출력 -> 출력: [1 2 3 4]
print(scalar)      # 더해지는 스칼라 값 출력 -> 출력: 1
print(result)      # 연산 결과 출력 -> 출력: [2 3 4 5]

# Shape(모양) 확인
print(arr.shape)   # 입력 배열의 shape -> 출력: (4,)
print(result.shape)# 결과 배열의 shape -> 출력: (4,)

[1 2 3 4]
1
[2 3 4 5]
(4,)
(4,)


In [224]:
import numpy as np

# 1. shape (4, 3) 크기의 2차원 배열 생성
matrix = np.array([[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]])

# 2. shape (3,) 크기의 1차원 배열 생성
row_vec = np.array([0, 1, 2])

# 3. 2차원 배열과 1차원 배열의 덧셈 연산 (브로드캐스팅 발생)
#    shape (3,) 배열이 axis 0(행 방향, 아래쪽)으로 확장되어 
#    [[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]의 형태로 각 행에 더해집니다.
result = matrix + row_vec

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(matrix)
# 출력:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

print(row_vec)
# 출력: [0 1 2]

print(result)
# 출력:
# [[ 0  2  4]
#  [ 3  5  7]
#  [ 6  8 10]
#  [ 9 11 13]]

# Shape(모양) 확인
print(matrix.shape)   # 2차원 배열 크기 -> 출력: (4, 3)
print(row_vec.shape)  # 1차원 배열 크기 -> 출력: (3,)
print(result.shape)   # 연산 결과 배열 크기 -> 출력: (4, 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
(4, 3)
(3,)
(4, 3)


In [225]:
import numpy as np

# 1. shape (4, 3) 크기의 2차원 배열 생성
matrix = np.array([[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8],
                   [ 9, 10, 11]])

# 2. shape (4, 1) 크기의 2차원 열벡터(Column Vector) 생성
col_vec = np.array([[0],
                    [1],
                    [2],
                    [3]])

# 3. 2차원 배열 간의 덧셈 연산 (브로드캐스팅 발생)
#    shape (4, 1) 배열이 axis 1(열 방향, 오른쪽)으로 확장되어 
#    [[0, 0, 0], [1, 1, 1], [2, 2, 2], [3, 3, 3]] 형태가 되어 각 열에 더해집니다.
result = matrix + col_vec

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(matrix)
# 출력:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]]

print(col_vec)
# 출력:
# [[0]
#  [1]
#  [2]
#  [3]]

print(result)
# 출력:
# [[ 0  1  2]
#  [ 4  5  6]
#  [ 8  9 10]
#  [12 13 14]]

# Shape(모양) 확인
print(matrix.shape)   # 첫 번째 2차원 배열 크기 -> 출력: (4, 3)
print(col_vec.shape)  # 두 번째 2차원 배열(열벡터) 크기 -> 출력: (4, 1)
print(result.shape)   # 연산 결과 배열 크기 -> 출력: (4, 3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
(4, 3)
(4, 1)
(4, 3)


In [226]:
import numpy as np

# 1. shape (2, 4, 3) 크기의 3차원 배열 생성
array_3d = np.array([
    [[ 0,  1,  2],
     [ 3,  4,  5],
     [ 6,  7,  8],
     [ 9, 10, 11]],

    [[12, 13, 14],
     [15, 16, 17],
     [18, 19, 20],
     [21, 22, 23]]
])

# 2. shape (4, 3) 크기의 2차원 배열 생성 (모든 원소가 1인 배열)
array_2d = np.ones((4, 3), dtype=int)

# 3. 3차원 배열과 2차원 배열 간의 덧셈 연산 (브로드캐스팅 발생)
#    shape (4, 3) 배열이 axis 0(깊이 축, 뒤쪽 면) 방향으로 2번 복사되어
#    3차원 배열의 첫 번째 면과 두 번째 면 각각에 모두 더해집니다.
result = array_3d + array_2d

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(array_3d)
# 출력:
# [[[ 0  1  2]
#   [ 3  4  5]
#   [ 6  7  8]
#   [ 9 10 11]]
#
#  [[12 13 14]
#   [15 16 17]
#   [18 19 20]
#   [21 22 23]]]

print(array_2d)
# 출력:
# [[1 1 1]
#  [1 1 1]
#  [1 1 1]
#  [1 1 1]]

print(result)
# 출력:
# [[[ 1  2  3]
#   [ 4  5  6]
#   [ 7  8  9]
#   [10 11 12]]
#
#  [[13 14 15]
#   [16 17 18]
#   [19 20 21]
#   [22 23 24]]]

# Shape(모양) 확인
print(array_3d.shape)  # 3차원 배열 크기 -> 출력: (2, 4, 3)
print(array_2d.shape)  # 2차원 배열 크기 -> 출력: (4, 3)
print(result.shape)    # 연산 결과 배열 크기 -> 출력: (2, 4, 3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
(2, 4, 3)
(4, 3)
(2, 4, 3)


## 3.3 **축(Axis)의 개념**: `axis=0`(행 축/열 기준)과 `axis=1`(열 축/행 기준)의 완벽한 시각적 이해

**1)한 눈에 보는 축(Axis) 방향 요약**

!image.png

**2)왜 이름이 이렇게 붙었을까? (원리 이해)**

### ① `axis = 0` (세로 방향 / 행 축)

- **방향:** 위에서 아래로 세로(⬇)로 움직인다.
- **연산 동작:** "행(Row)들을 하나씩 거쳐가며(주르륵 내려가며) 연산"한다.
- **결과적 관점 (열 기준):** 세로로 내려가면서 연산하기 때문에, 결과적으로 **각 열(Column)별 합계/평균**이 구해진다.

### ② `axis = 1` (가로 방향 / 열 축)

- **방향:** 왼쪽에서 오른쪽으로 가로(➔)로 움직인다.
- **연산 동작:** "열(Column)들을 하나씩 거쳐가며(옆으로 이동하며) 연산"한다.
- **결과적 관점 (행 기준):** 가로로 옆으로 이동하며 연산하기 때문에, 결과적으로 **각 행(Row)별 합계/평균**이 구해진다.

**3) 코드와 결과를 통한 직관적 이해**
다음과 같은 **3 X 3** 행렬

In [227]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

`np.sum(arr, axis=0)` ➔ 세로 연산 (행들을 접는다)

`axis=0`은 위에서 아래로(세로로) 수식을 적용한다.

```python
  1    2    3
  +    +    +   (세로 방향 ⬇ 연산)
  4    5    6
  +    +    +
  7    8    9
 ───  ───  ───
 12   15   18   ➔ 결과
```

In [228]:
print(np.sum(arr, axis=0))  
# 출력: [12 15 18]  (각 열의 합)

[12 15 18]


`np.sum(arr, axis=1)` ➔ 가로 연산 (열들을 접는다)

`axis=1`은 왼쪽에서 오른쪽으로(가로로) 수식을 적용한다.

```python
 1 + 2 + 3  ➔  6   (가로 방향 ➔ 연산)
 4 + 5 + 6  ➔ 15
 7 + 8 + 9  ➔ 24
```

In [229]:
print(np.sum(arr, axis=1))  
# 출력: [ 6 15 24]  (각 행의 합)

[ 6 15 24]


 **4) 암기 꿀팁 (헷갈릴 때 기억하는 방법)"지우개 법칙 (축을 없앤다!)"**

- `shape (3, 3)` 형태의 2차원 배열이 있을 때:
  - `axis=0`으로 연산하면 (3, 3)중  첫 번째 3(행 축)이 지워져 결과는 **`shape (3,)`** (세로 연산 결과)가 된다.
  - `axis=1`로 연산하면 (3, 3) 중 두 번째 3(열 축)이 지워져 결과는 **`shape (3,)`** (가로 연산 결과)가 된다.

즉, **`axis=n`은 "N번째 차원 방향으로 데이터들을 뭉개서 하나로 합친다!"** 라고 이해하시면 가장 쉽다.

## 3.4 집계 함수: np.sum(), np.mean(), np.std(), np.min(), np.max() 연산 및 축별 활용법

In [230]:
import numpy as np

# 1. 1차원 배열 생성 (색인/Index: 0~5)
x = np.array([5, 4, 3, 2, 1, 0])

# 2. 통계 함수 연산
max_val = np.max(x)    # 최대값
min_val = np.min(x)    # 최소값
sum_val = np.sum(x)    # 합계
mean_val = np.mean(x)  # 평균
std_val = np.std(x)    # 표준편차

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x)        # 입력 배열 -> 출력: [5 4 3 2 1 0]

# 1) 최대값 (np.max)
print(max_val)  # 출력: 5

# 2) 최소값 (np.min)
print(min_val)  # 출력: 0

# 3) 합계 (np.sum)
# 계산식: 5 + 4 + 3 + 2 + 1 + 0 = 15
print(sum_val)  # 출력: 15

# 4) 평균 (np.mean)
# 계산식: 15 / 6 = 2.5
print(mean_val) # 출력: 2.5

# 5) 표준편차 (np.std)
# 계산식: sqrt(((5-2.5)^2 + (4-2.5)^2 + ... + (0-2.5)^2) / 6) = sqrt(17.5 / 6)
print(std_val)  # 출력: 1.707825127659933  (약 1.708)

[5 4 3 2 1 0]
5
0
15
2.5
1.707825127659933


## 3.5 위치 찾기: np.argmax(), np.argmin()을 활용한 최대/최소값의 인덱스 번호 추출

In [231]:
import numpy as np

# 1. 1차원 배열 생성 (색인/Index: 0~5)
#    값(Value)   : [5, 4, 3, 2, 1, 0]
#    인덱스(Index): [0, 1, 2, 3, 4, 5]
x = np.array([5, 4, 3, 2, 1, 0])

# 2. 인덱스 추출 함수 연산
argmax_val = np.argmax(x)  # 가장 큰 값의 인덱스(위치)
argmin_val = np.argmin(x)  # 가장 작은 값의 인덱스(위치)

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x)           # 입력 배열 -> 출력: [5 4 3 2 1 0]

# 1) 가장 큰 값의 인덱스 (np.argmax)
# 가장 큰 값은 '5'이며, 이 값이 위치한 인덱스는 '0'입니다.
print(argmax_val)  # 출력: 0

# 2) 가장 작은 값의 인덱스 (np.argmin)
# 가장 작은 값은 '0'이며, 이 값이 위치한 인덱스는 '5'입니다.
print(argmin_val)  # 출력: 5

[5 4 3 2 1 0]
0
5


# 4. 실무 데이터 처리 기법 및 미니 프로젝트

**강의 목표**: 조건부 데이터 정제 기술을 익히고, 머신러닝 전처리에 쓰이는 선형대수 기초를 실습한다.

## 4.1 **조건 처리 함수**: `np.where()`를 활용한 이상치 대체 및 삼항 연산 구현

In [232]:
import numpy as np

# 1. 1차원 배열 생성 (색인/Index: 0~5)
#    값(Value)   : [5, 4, 3, 2, 1, 0]
#    인덱스(Index): [0, 1, 2, 3, 4, 5]
x = np.array([5, 4, 3, 2, 1, 0])

# 2. 통계 및 조건부 추출 연산
max_val = np.max(x)                 # 최대값
min_val = np.min(x)                 # 최소값
where_idx = np.where(x >= 3)        # 조건(x >= 3)을 만족하는 인덱스 추출
where_val = x[np.where(x >= 3)]     # 조건(x >= 3)에 해당하는 실제 값들 추출

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x)                  # 입력 배열 -> 출력: [5 4 3 2 1 0]

# 1) 최대값 (np.max)
print(max_val)            # 출력: 5

# 2) 최소값 (np.min)
print(min_val)            # 출력: 0

# 3) 조건에 해당하는 인덱스 위치 (np.where(x >= 3))
#    x >= 3 조건(5, 4, 3)을 만족하는 위치의 인덱스 [0, 1, 2] 반환
print(where_idx)          # 출력: (array([0, 1, 2]),)

# 4) 조건에 해당하는 실제 값 (x[np.where(x >= 3)])
#    인덱스 [0, 1, 2]에 위치한 실제 요소들을 추출
print(where_val)          # 출력: [5 4 3]

[5 4 3 2 1 0]
5
0
(array([0, 1, 2]),)
[5 4 3]


## 4.2 정렬 및 중복 제거: np.sort(), 인덱스를 반환하는 argsort(), 유일한 값 추출 np.unique()

In [233]:
import numpy as np

# 1. 2차원 배열 x2 생성 (shape: 3x3)
x2 = np.array([[2, 1, 6],
               [0, 7, 4],
               [5, 3, 2]])

# 2. 정렬 연산
# ① 좌에서 우로 정렬 (axis=1: 행 내부에서 가로 방향 정렬)
sort_axis1 = np.sort(x2, axis=1)

# ② 위에서 아래로 정렬 (axis=0: 열 내부에서 세로 방향 정렬)
sort_axis0 = np.sort(x2, axis=0)

# ③ 아래에서 위로 거꾸로 정렬 (axis=0 정렬 후 행 순서 뒤집기)
sort_axis0_reverse = np.sort(x2, axis=0)[::-1]

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(x2)
# 원본 배열 출력:
# [[2 1 6]
#  [0 7 4]
#  [5 3 2]]

# ① np.sort(x2, axis=1) -> 좌에서 우로 정렬
print(sort_axis1)
# 출력:
# [[1 2 6]
#  [0 4 7]
#  [2 3 5]]

# ② np.sort(x2, axis=0) -> 위에서 아래로 정렬
print(sort_axis0)
# 출력:
# [[0 1 2]
#  [2 3 4]
#  [5 7 6]]

# ③ np.sort(x2, axis=0)[::-1] -> 아래에서 위로 거꾸로 정렬
print(sort_axis0_reverse)
# 출력:
# [[5 7 6]
#  [2 3 4]
#  [0 1 2]]

[[2 1 6]
 [0 7 4]
 [5 3 2]]
[[1 2 6]
 [0 4 7]
 [2 3 5]]
[[0 1 2]
 [2 3 4]
 [5 7 6]]
[[5 7 6]
 [2 3 4]
 [0 1 2]]


## 4.3 **선형대수 기초 (Linear Algebra)**:

선형대수학은 벡터 공간, 선형 변환, 행렬 등을 연구하는 수학의 한 분야이다. 데이터 과학, 머신러닝, 인공지능 분야에서 핵심이 되는 수학적 기초를 제공한다.

### 1) 주요 개념 정리

- **스칼라(Scalar)**: 크기만을 가지는 단일 숫자이다.
- **벡터(Vector)**: 크기와 방향을 동시에 가지며, 공간 상의 한 점이나 방향을 나타낸다.
- **행렬(Matrix)**: 숫자들을 가로(행)와 세로(열)로 배열한 2차원 구조이다.
- **텐서(Tensor)**: 행렬을 3차원 이상으로 확장한 다차원 배열이다.
- **선형 변환(Linear Transformation)**: 공간 상의 벡터를 다른 벡터로 매핑할 때, 가산성과 제차성을 만족하는 변환이다.
- **고유값과 고유벡터(Eigenvalue & Eigenvector)**: 선형 변환을 적용했을 때 방향은 바뀌지 않고 크기만 변하는 벡터를 고유벡터라 하며, 그 크기의 변화 비율을 고유값이라 한다.

In [234]:
import numpy as np

# 1. 벡터 및 행렬 생성
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# 2. 벡터 내적 (Dot Product)
dot_product = np.dot(v1, v2)
print("Vector Dot Product:")
print(dot_product)
# 출력: 32 (1*4 + 2*5 + 3*6)

# 3. 행렬 곱셈 (Matrix Multiplication)
matrix_mul = np.matmul(A, B) # 또는 A @ B
print("\nMatrix Multiplication (A @ B):")
print(matrix_mul)
# 출력:
# [[19 22]
#  [43 50]]

# 4. 전치 행렬 (Transpose Matrix)
A_transpose = A.T
print("\nTranspose of Matrix A:")
print(A_transpose)
# 출력:
# [[1 3]
#  [2 4]]

# 5. 역행렬 (Inverse Matrix)
A_inv = np.linalg.inv(A)
print("\nInverse of Matrix A:")
print(A_inv)
# 출력:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# 6. 행렬식 (Determinant)
det_A = np.linalg.det(A)
print("\nDeterminant of Matrix A:")
print(det_A)
# 출력: -2.0 (1*4 - 2*3)

# 7. 고유값 및 고유벡터 (Eigenvalues & Eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigenvalues)
# 출력: [-0.37228132  5.37228132]

print("\nEigenvectors of A:")
print(eigenvectors)
# 출력:
# [[-0.82456484 -0.41597356]
#  [ 0.56576746 -0.90937671]]

Vector Dot Product:
32

Matrix Multiplication (A @ B):
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinant of Matrix A:
-2.0000000000000004

Eigenvalues of A:
[-0.37228132+0.j  5.37228132+0.j]

Eigenvectors of A:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]


행렬 곱(`np.dot()`, `@` 연산자), 전치행렬(`.T`)

- ndarray에서 행렬곱 연산자 @ 이다.
- python 재단에서 numpy를 위해 만들어준 연산자이다

In [235]:
import numpy as np

# 1. shape (3, 5) 크기의 2차원 배열 생성
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

# 2. 전치(Transpose) 및 축 교환(Swap Axes) 연산 (모두 동일한 결과 반환)
# ① .T 속성 사용
transposed_T = a.T

# ② np.transpose() 함수 사용
transposed_func = np.transpose(a)

# ③ np.swapaxes() 함수 사용 (0번 축과 1번 축을 맞바꿈)
swapped = np.swapaxes(a, 0, 1)

# ==============================================================================
# 출력 및 결과
# ==============================================================================
print(a)
# 원본 배열 출력 (shape: 3, 5):
# [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]]

# ① a.T -> 전치 행렬
print(transposed_T)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ② np.transpose(a) -> 전치 행렬
print(transposed_func)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# ③ np.swapaxes(a, 0, 1) -> 축 맞바꿈
print(swapped)
# 출력:
# [[ 0  5 10]
#  [ 1  6 11]
#  [ 2  7 12]
#  [ 3  8 13]
#  [ 4  9 14]]

# Shape(모양) 확인 ( (3, 5) -> (5, 3)으로 변환 )
print(a.shape)            # 원본 크기 -> 출력: (3, 5)
print(transposed_T.shape) # 변환 후 크기 -> 출력: (5, 3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(3, 5)
(5, 3)


In [236]:
b = np.matrix([[1,2], [3,4]]) # 행렬 생성  [[1 2][3 4]]
print(b)

print(type(b))            # numpy.matrix

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [238]:
b * b
#  1*1 + 2*3=7    1*2+2*4=10
#  3*1 + 4*3=15   3*2+4*4=22

# [[1*1+2*3   1*2+2*4]      [[7,10]
#  [3*1+4*3   3*2+4*4]]      [15,22]]

# (2,2)  (2,2)  # 앞의 행과 뒤의 열의 갯수가 같아야 한다.

# ```
# matrix([[ 7, 10],
#         [15, 22]])
# ```

matrix([[ 7, 10],
        [15, 22]])

```python

```

배열은 @가능하지만 *은 사용 할 수 없다.

matrix는 * 와 @ 모두가 가능하다.

ndarray에서 행렬곱 연산자 @ 이다.  
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [240]:
c = np.matrix([[1,2], [3,4]]) # 행렬 생성
print(c)

print(c)
print(c.shape)

print(c * c.T)  # 함수방법으로 np.dot( )함수를 사용할 수 있다.
print( c.dot(c.T) ) # 메소드(method) 방식
print(c @ c.T)

# ```
# matrix([[ 5, 11],
#         [11, 25]])
#  ```
 
 


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
(2, 2)
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]


## **4.4 종합 미니 프로젝트 (실전 실습)**:

[예시 1] NumPy만으로 가상의 학생 성적 데이터셋 생성, 평균/표준편차 구하기, 낙제점 수정하기

학생 5명의 3개 과목(국어, 영어, 수학) 성적 데이터를 생성하고, 통계량 계산 및 기준 이하 점수(낙제점)를 수정하는 전처리 과정이다.

In [244]:

import numpy as np

# # 1. 시드 고정 및 가상의 학생 성적 데이터셋 생성 (학생 5명, 과목 3개)
np.random.seed(42)
scores = np.random.randint(40, 101, size=(5, 3))

print("1. 원본 성적 데이터셋 (5명 x 3과목):")
print(scores)

# 2. 각 과목별 평균 및 표준편차 구하기 (axis=0: 세로/열 방향 연산)
subject_mean = np.mean(scores, axis=0)
subject_std = np.std(scores, axis=0)

print("\n2. 과목별 평균:")
print(subject_mean)

print("\n3. 과목별 표준편차:")
print(np.round(subject_std, 2))

# 3. 각 학생별 평균 구하기 (axis=1: 가로/행 방향 연산)
student_mean = np.mean(scores, axis=1)

print("\n4. 학생별 평균 점수:")
print(np.round(student_mean, 2))

# 4. 낙제점 수정하기 (60점 미만인 점수를 60점으로 일괄 수정)
# np.where(조건, 참일 때 값, 거짓일 때 값) 활용
fixed_scores = np.where(scores < 60, 60, scores)

print("\n5. 낙제점(60점 미만) 수정 후 데이터셋:")
print(fixed_scores)


1. 원본 성적 데이터셋 (5명 x 3과목):
[[ 78  91  68]
 [ 54  82  47]
 [100  60  78]
 [ 97  58  62]
 [ 50  50  63]]

2. 과목별 평균:
[75.8 68.2 63.6]

3. 과목별 표준편차:
[20.88 15.57 10.05]

4. 학생별 평균 점수:
[79.   61.   79.33 72.33 54.33]

5. 낙제점(60점 미만) 수정 후 데이터셋:
[[ 78  91  68]
 [ 60  82  60]
 [100  60  78]
 [ 97  60  62]
 [ 60  60  63]]


[예시 2] 단순 이미지 픽셀 데이터(3차원 배열)를 불러와 흑백 전환 및 크기 조절 전처리 구현

$(H, W, C)$ 구조의 3차원 RGB 이미지 데이터를 생성하여 표준 공식을 통한 흑백(Grayscale) 전환 및 다운샘플링(크기 조절)을 구현하는 코드이다.

In [243]:

import numpy as np

# 1. 가상의 RGB 이미지 픽셀 데이터 생성 (높이 4 x 너비 4 x 채널 3)
np.random.seed(100)
image_rgb = np.random.randint(0, 256, size=(4, 4, 3), dtype=np.uint8)

print("1. 원본 RGB 이미지 Shape:")
print(image_rgb.shape)

# 2. RGB 흑백 전환 (Grayscale Conversion)
# ITU-R BT.601 표준 공식: Y = 0.299*R + 0.587*G + 0.114*B
# 채널 축(axis 2)에 가중치를 내적(Dot Product)하거나 브로드캐스팅하여 계산함
weights = np.array([0.299, 0.587, 0.114])
image_gray = np.dot(image_rgb, weights).astype(np.uint8)

print("\n2. 흑백 전환 후 이미지 Shape:")
print(image_gray.shape)  # (4, 4)로 차원 축소됨

print("\n3. 흑백 이미지 픽셀 값:")
print(image_gray)

# 3. 이미지 크기 조절 (Downsampling / Resizing)
# 슬라이싱([::2, ::2])을 이용하여 가로/세로 픽셀을 2칸씩 스킵함으로써 크기를 1/2로 줄임
image_resized = image_gray[::2, ::2]

print("\n4. 크기 조절(2x2로 축소) 후 이미지 Shape:")
print(image_resized.shape)

print("\n5. 최종 축소된 이미지 픽셀 값:")
print(image_resized)


1. 원본 RGB 이미지 Shape:
(4, 4, 3)

2. 흑백 전환 후 이미지 Shape:
(4, 4)

3. 흑백 이미지 픽셀 값:
[[ 93  80 170  63]
 [175  87 124 128]
 [ 97 173  36  50]
 [ 89  73  33 139]]

4. 크기 조절(2x2로 축소) 후 이미지 Shape:
(2, 2)

5. 최종 축소된 이미지 픽셀 값:
[[ 93 170]
 [ 97  36]]
