In [2]:
data = [1,2,3,4]
result = []

for i in data:
    result.append(i*10)

print(result)

[10, 20, 30, 40]


In [5]:
import numpy as np

arr = np.array([1,2,3,4])
arr10 = arr*10
print(arr10)

[10 20 30 40]


In [6]:
import numpy as np

In [7]:
data = [1,2,3,4]
data * 10

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [9]:
arr = np.array(data)

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(data)

list

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
arr *10

array([10, 20, 30, 40])

In [ ]:
price= [
    [1]
]